version: '2'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
      args:
        app_version: ${APP_VERSION}
    environment:
      HTTP_HOST: app
      HTTP_PORT: 8000
      CLUSTER_GROUP_NAME: audit-service
      CLUSTER_GROUP_PASSWORD: password
      JDBC_URL: jdbc:mysql://db/${DB_NAME}?username=${DB_USER}&password=${DB_PASSWORD}
      JDBC_DRIVERCLASS: com.mysql.jdbc.Driver
    command:
      - java
      - -jar
      - /app/audit-service-${APP_VERSION}-fat.jar
      - -conf=/app/conf/config.json
      - -Dvertx.hazelcast.config=/app/conf/cluster.xml
      - -cluster
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  agent:
    image: dockerproductionaws/ansible
    links:
      - db
    environment:
      PROBE_HOST: db
      PROBE_PORT: 3306
  test:
    image: dockerproductionaws/microtrader-test
    links:
      - app
    environment:
      CLUSTER_GROUP_NAME: audit-service
      CLUSTER_GROUP_PASSWORD: password
    command:
      - mvn
      - test
      - -Dtest=AuditServiceTest
      - -Dvertx.hazelcast.config=/app/conf/cluster.xml
